### PR TITLE
Complete Turquoise Calendar

### PR DESCRIPTION
**Pull request by W-Floyd**
~~Also rebases on master.~~

### CODE REVIEW

**Comment by mueller-ma** [comment]
This PR has over 250 commits. I dont think that's what you want.

**Comment by W-Floyd** [comment]
I'll not rebase on master then.

**Comment by W-Floyd** [comment]
Should be good now.

**Comment by W-Floyd** [comment]
iconified_calendar-turquoise-01
iconified_calendar-turquoise-02
iconified_calendar-turquoise-03
iconified_calendar-turquoise-04
iconified_calendar-turquoise-05
iconified_calendar-turquoise-06
iconified_calendar-turquoise-07
iconified_calendar-turquoise-08
iconified_calendar-turquoise-09
iconified_calendar-turquoise-10
iconified_calendar-turquoise-11
iconified_calendar-turquoise-12
iconified_calendar-turquoise-13
iconified_calendar-turquoise-14
iconified_calendar-turquoise-15
iconified_calendar-turquoise-16
iconified_calendar-turquoise-17
iconified_calendar-turquoise-18
iconified_calendar-turquoise-19
iconified_calendar-turquoise-20
iconified_calendar-turquoise-21
iconified_calendar-turquoise-22
iconified_calendar-turquoise-23
iconified_calendar-turquoise-24
iconified_calendar-turquoise-25
iconified_calendar-turquoise-26
iconified_calendar-turquoise-27
iconified_calendar-turquoise-28
iconified_calendar-turquoise-29
iconified_calendar-turquoise-30
iconified_calendar-turquoise-31

**Comment by mueller-ma** [comment]
Thanks!

**Comment by W-Floyd** [comment]
No problem :)

**Pull request merged**
